// <auto-generated />
using System;
using FlightService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightService.Migrations
{
    [DbContext(typeof(FlightServiceDbContext))]
    [Migration("20251228181507_AddAllDbRelationsAndFixAirlineColumn")]
    partial class AddAllDbRelationsAndFixAirlineColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightService.Models.Airline", b =>
                {
                    b.Property<int>("airline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airline_id"));

                    b.Property<string>("airlinename")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("base_airport")
                        .HasColumnType("integer");

                    b.Property<string>("iata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("airline_id");

                    b.HasIndex("base_airport");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("FlightService.Models.Airplane", b =>
                {
                    b.Property<int>("airplane_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airplane_id"));

                    b.Property<int>("airline_id")
                        .HasColumnType("integer");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<int>("type_id")
                        .HasColumnType("integer");

                    b.HasKey("airplane_id");

                    b.HasIndex("airline_id");

                    b.HasIndex("type_id");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("FlightService.Models.Airplane_type", b =>
                {
                    b.Property<int>("type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("type_id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("identifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("type_id");

                    b.ToTable("Airplane_type");
                });

            modelBuilder.Entity("FlightService.Models.Airport", b =>
                {
                    b.Property<int>("airport_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airport_id"));

                    b.Property<string>("iata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("airport_id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightService.Models.AirportGeo", b =>
                {
                    b.Property<int>("airport_id")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("airport_id");

                    b.ToTable("AirportGeos");
                });

            modelBuilder.Entity("FlightService.Models.AirportStaff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StaffId"));

                    b.Property<int?>("AirlineId")
                        .HasColumnType("integer")
                        .HasColumnName("airline_id");

                    b.Property<int?>("AirportId")
                        .HasColumnType("integer")
                        .HasColumnName("airport_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_reset_expires");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_reset_token");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("StaffId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("AirportId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AirportStaff");
                });

            modelBuilder.Entity("FlightService.Models.Airport_reachable", b =>
                {
                    b.Property<int>("airport_id")
                        .HasColumnType("integer");

                    b.Property<int>("hops")
                        .HasColumnType("integer");

                    b.HasKey("airport_id");

                    b.ToTable("Airport_reachable");
                });

            modelBuilder.Entity("FlightService.Models.Booking", b =>
                {
                    b.Property<int>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("booking_id"));

                    b.Property<int>("flight_id")
                        .HasColumnType("integer");

                    b.Property<int>("passenger_id")
                        .HasColumnType("integer");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("seat")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("booking_id");

                    b.HasIndex("flight_id");

                    b.HasIndex("passenger_id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightService.Models.Flight", b =>
                {
                    b.Property<int>("flight_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("flight_id"));

                    b.Property<int>("airline_id")
                        .HasColumnType("integer");

                    b.Property<int>("airplane_id")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("arrival")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("departure")
                        .HasColumnType("time without time zone");

                    b.Property<string>("flightno")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("from")
                        .HasColumnType("integer");

                    b.Property<int>("to")
                        .HasColumnType("integer");

                    b.HasKey("flight_id");

                    b.HasIndex("airline_id");

                    b.HasIndex("airplane_id");

                    b.HasIndex("from");

                    b.HasIndex("to");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightService.Models.FlightSchedule", b =>
                {
                    b.Property<int>("flightno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("flightno"));

                    b.Property<int>("airline_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("arrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("departure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("friday")
                        .HasColumnType("integer");

                    b.Property<int>("from")
                        .HasColumnType("integer");

                    b.Property<int>("monday")
                        .HasColumnType("integer");

                    b.Property<int>("saturday")
                        .HasColumnType("integer");

                    b.Property<int>("sunday")
                        .HasColumnType("integer");

                    b.Property<int>("thursday")
                        .HasColumnType("integer");

                    b.Property<int>("to")
                        .HasColumnType("integer");

                    b.Property<int>("tuesday")
                        .HasColumnType("integer");

                    b.Property<int>("wednesday")
                        .HasColumnType("integer");

                    b.HasKey("flightno");

                    b.HasIndex("airline_id");

                    b.HasIndex("from");

                    b.HasIndex("to");

                    b.ToTable("FlightSchedules");
                });

            modelBuilder.Entity("FlightService.Models.Passenger", b =>
                {
                    b.Property<int>("passenger_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("passenger_id"));

                    b.Property<string>("Passportno")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("passenger_id");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlightService.Models.Passenger_details", b =>
                {
                    b.Property<int>("passenger_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("sex")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("telephone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("zip")
                        .HasColumnType("integer");

                    b.HasKey("passenger_id");

                    b.ToTable("Passenger_details");
                });

            modelBuilder.Entity("FlightService.Models.Airline", b =>
                {
                    b.HasOne("FlightService.Models.Airport", "BaseAirport")
                        .WithMany()
                        .HasForeignKey("base_airport")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseAirport");
                });

            modelBuilder.Entity("FlightService.Models.Airplane", b =>
                {
                    b.HasOne("FlightService.Models.Airline", "Airline")
                        .WithMany("Airplanes")
                        .HasForeignKey("airline_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Airplane_type", "AirplaneType")
                        .WithMany()
                        .HasForeignKey("type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("AirplaneType");
                });

            modelBuilder.Entity("FlightService.Models.AirportGeo", b =>
                {
                    b.HasOne("FlightService.Models.Airport", null)
                        .WithOne("AirportGeo")
                        .HasForeignKey("FlightService.Models.AirportGeo", "airport_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlightService.Models.AirportStaff", b =>
                {
                    b.HasOne("FlightService.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FlightService.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Airline");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("FlightService.Models.Airport_reachable", b =>
                {
                    b.HasOne("FlightService.Models.Airport", null)
                        .WithOne("AirportReachable")
                        .HasForeignKey("FlightService.Models.Airport_reachable", "airport_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlightService.Models.Booking", b =>
                {
                    b.HasOne("FlightService.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("flight_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Passenger", "Passenger")
                        .WithMany("Bookings")
                        .HasForeignKey("passenger_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("FlightService.Models.Flight", b =>
                {
                    b.HasOne("FlightService.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("airline_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("airplane_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Airport", "FromAirport")
                        .WithMany()
                        .HasForeignKey("from")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Airport", "ToAirport")
                        .WithMany()
                        .HasForeignKey("to")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Airplane");

                    b.Navigation("FromAirport");

                    b.Navigation("ToAirport");
                });

            modelBuilder.Entity("FlightService.Models.FlightSchedule", b =>
                {
                    b.HasOne("FlightService.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("airline_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Airport", "FromAirport")
                        .WithMany()
                        .HasForeignKey("from")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlightService.Models.Airport", "ToAirport")
                        .WithMany()
                        .HasForeignKey("to")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("FromAirport");

                    b.Navigation("ToAirport");
                });

            modelBuilder.Entity("FlightService.Models.Passenger_details", b =>
                {
                    b.HasOne("FlightService.Models.Passenger", "Passenger")
                        .WithOne("PassengerDetails")
                        .HasForeignKey("FlightService.Models.Passenger_details", "passenger_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("FlightService.Models.Airline", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("Flights");
                });

            modelBuilder.Entity("FlightService.Models.Airport", b =>
                {
                    b.Navigation("AirportGeo")
                        .IsRequired();

                    b.Navigation("AirportReachable")
                        .IsRequired();
                });

            modelBuilder.Entity("FlightService.Models.Passenger", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PassengerDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
