// <auto-generated />
using System;
using FlightService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightService.Migrations
{
    [DbContext(typeof(FlightServiceDbContext))]
    [Migration("20251227104510_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightService.Models.Airline", b =>
                {
                    b.Property<int>("airline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airline_id"));

                    b.Property<string>("airlinename")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("base_airport")
                        .HasColumnType("integer");

                    b.Property<string>("iata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.HasKey("airline_id");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("FlightService.Models.Airplane", b =>
                {
                    b.Property<int>("airplane_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airplane_id"));

                    b.Property<int>("airline_id")
                        .HasColumnType("integer");

                    b.Property<int>("capacity")
                        .HasColumnType("integer");

                    b.Property<int>("type_id")
                        .HasColumnType("integer");

                    b.HasKey("airplane_id");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("FlightService.Models.Airport", b =>
                {
                    b.Property<int>("airport_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airport_id"));

                    b.Property<string>("iata")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("airport_id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("FlightService.Models.AirportGeo", b =>
                {
                    b.Property<int>("airport_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("airport_id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("airport_id");

                    b.ToTable("AirportGeos");
                });

            modelBuilder.Entity("FlightService.Models.Booking", b =>
                {
                    b.Property<int>("booking_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("booking_id"));

                    b.Property<int>("flight_id")
                        .HasColumnType("integer");

                    b.Property<int>("passenger_id")
                        .HasColumnType("integer");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.Property<string>("seat")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.HasKey("booking_id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("FlightService.Models.Flight", b =>
                {
                    b.Property<int>("flight_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("flight_id"));

                    b.Property<int>("airline_id")
                        .HasColumnType("integer");

                    b.Property<int>("airplane_id")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("arrival")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("departure")
                        .HasColumnType("time without time zone");

                    b.Property<string>("flightno")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("from")
                        .HasColumnType("integer");

                    b.Property<int>("to")
                        .HasColumnType("integer");

                    b.HasKey("flight_id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("FlightService.Models.FlightSchedule", b =>
                {
                    b.Property<int>("flightno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("flightno"));

                    b.Property<int>("airline_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("arrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("departure")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("friday")
                        .HasColumnType("integer");

                    b.Property<int>("from")
                        .HasColumnType("integer");

                    b.Property<int>("monday")
                        .HasColumnType("integer");

                    b.Property<int>("saturday")
                        .HasColumnType("integer");

                    b.Property<int>("sunday")
                        .HasColumnType("integer");

                    b.Property<int>("thursday")
                        .HasColumnType("integer");

                    b.Property<int>("to")
                        .HasColumnType("integer");

                    b.Property<int>("tuesday")
                        .HasColumnType("integer");

                    b.Property<int>("wednesday")
                        .HasColumnType("integer");

                    b.HasKey("flightno");

                    b.ToTable("FlightSchedules");
                });

            modelBuilder.Entity("FlightService.Models.Passenger", b =>
                {
                    b.Property<int>("passenger_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("passenger_id"));

                    b.Property<string>("Passportno")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("passenger_id");

                    b.ToTable("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
